spring:
  application:
    name: quickstart
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf-8&useInformationSchema=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: leonardo123
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 8
          # 连接池最大空闲连接数
          max-idle: 8
          # 连接池最小空闲连接数
          min-idle: 0
          # 连接池最大阻塞等待时间（-1表示无限制）
          max-wait: -1ms
      # 连接超时时间
      timeout: 3000ms
  # h2:
  #   console:
  #     settings:
  #       web-allow-others: true
  #     enabled: true
  #     path: /h2-console
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.H2Dialect
  #   show-sql: true

server:
  port: 9101
  servlet:
    context-path: /${spring.application.name}

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /openapi-doc.html

logging:
  config: classpath:logback-spring.xml

